### ISSUE TITLE
نمایش اطلاعات بر اساس email (یوزر)

### ISSUE THREAD

**Issue by uzer98** [Kup1ng/Patrick#1]
اگه بتونید نمایش اطلاعات بر اساس email (یوزر) هم اضافه کنید عالی میشه

**Comment by Kup1ng** [comment]
این روش نمایش برای کاربر ها مشکل ساز خواهد بود و ممکن است شما در چند پنل یک ایمیل داشته باشید و یا فروشنده کانفیگ های خودش را با عدد بده و کاربر مثلا بجای اینکه ایمیل را t60 وارد کنه t61 وارد کنه و از کانفیگ یکنفر دیگه به راحتی استفاده کنه

**Comment by uzer98** [comment]
مگه پنل برای نمایش اطلاعات نیست
چطور کاربر از کانفیگ یکنفر دیگه استفاده کنه


اگر برای نمایش نیست و کانفیگ هم نمایش میده بنظرم جالب نیست و بهتره فقط مشخصات رو‌نمایش بده

**Comment by ILYAGVC** [comment]
> مگه پنل برای نمایش اطلاعات نیست چطور کاربر از کانفیگ یکنفر دیگه استفاده کنه
> 
> اگر برای نمایش نیست و کانفیگ هم نمایش میده بنظرم جالب نیست و بهتره فقط مشخصات رو‌نمایش بده

یکی از ویژگی ها تغییر لینک اتصال هستش
بعلاوه شما میتونید کلیک اختصاصی که پاتریک برای هر کانفیگ میسازه رو به کاربر بدید تا کاربر هربار کانفیگ رو وارد نکنه
(لینک اختصاصی رو خوده کاربر هم میتونه برداره و استفاده کنه)
