### ISSUE TITLE
check online ربات

### ISSUE THREAD

**Issue by Mddddddddddddd** [Kup1ng/Patrick#2]
سلام وقت بخیر
من میخواستم کد اون دکمه check online ربات شما رو داشته باشم تا توی مرورگر داخلی تلگرام برام لینک باز شه 
ممکنه کدش رو بدید یا راهنمایی کنید که به نتیجه برسم ؟
ممنونم

**Comment by ILYAGVC** [comment]
درود
پروژه اپن سورس نیست
